spring:
#  profiles:
#    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    # url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:./data/testDB;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  resources:
# enable H2 web console and set url for web console
# http://localhost:8080/console
h2:
  console:
    enabled: true
    path: /console
    port: 8082
server:
    context-path: /api
    port: 8081
com:
    testservice:
        global:
          debug: true
logging:
  file: ./logs/springboot.log
  # default level is INFO
  level:
    ROOT: debug
    org.springframework: debug
    org.springframework.scheduling: info